version: '2'
services:
  django:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
    env_file: .env
    command: django-admin runserver 0.0.0.0:8000
